<script type="text/javascript">
    function sendreminders() {
        var send = 1;
        new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
            method: 'Post',
            parameters: {send:send},
            onComplete: function(transport) {
                if ($('send_span').hasClassName('no-display')) {
                    $('send_span').setStyle({
                        'margin-left' : '10px', 
                        'font-weight' : 'bold',
                        'font-size'   : '12px'
                    });
                    $('send_span').removeClassName('no-display');
                }
           }
        });
    }
</script>
<?php echo $this->getButtonHtml() ?><span class="no-display" id="send_span"><?php echo $this->__('Reminders sent!')?></span>