<?php
    $reviews = $this->getReviewsCollection();
?>
<div class="page-title">
    <h1><?php echo $this->__('Reviews'); ?></h1>
</div>
<?php foreach ($reviews as $review): ?>                  
    <div class="review-customer">
        <div class="review-customer-message"><p><?php echo '&ldquo;'.$review->getMessage().'&rdquo;'; ?></p></div>
        
        <div class="review-customer-name"><?php   echo $review->getName(); ?></div>
    </div>  
<?php endforeach; ?> 