<?php 
    $order_id = $this->getRequest()->getParam('order_id'); 
?>
<div class="page-title">
    <h1><?php echo $this->__('Review'); ?></h1>
</div>
<form action="<?php echo $this->getUrl('customerreviews/index/post'); ?>" id="customerreviewsForm" class="customerreviewsForm" method="post" enctype="multipart/form-data">
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo $this->__('Name') ?></label>
                    <div class="input-box">
                       <input name="name" id="name"
                       title="<?php echo $this->__('Name') ?>"
                       value="<?php echo $this->escapeHtml($this->getCustomerData()->getName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo $this->__('Email') ?>" value="<?php echo $this->escapeHtml($this->getCustomerData()->getEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            
                <div class="field">
                    <label><?php echo $this->__('Rating delivery') ?></label>
                    <div class="input-box">
                    <?php for ($i = 1; $i <= 5; ++$i) { ?>
                        <label for="rating_delivery<?php echo $i; ?>"><?php echo $i; ?>
                            <input type="radio" name="rating_delivery" id="rating_delivery<?php echo $i; ?>" value="<?php echo $i; ?>" class="radio"  />
                        </label>
                    <?php } ?>
                        <div id="customerreviews-rating-box" style="display: none;" class="rating-box"><div id="customerreviews-rating" class="rating" style="width: 0"></div></div>
                    </div>
                </div>
                <div class="field">
                    <label><?php echo $this->__('Rating product') ?></label>
                    <div class="input-box">
                    <?php for ($i = 1; $i <= 5; ++$i) { ?>
                        <label for="rating_product<?php echo $i; ?>"><?php echo $i; ?>
                            <input type="radio" name="rating_product" id="rating_product<?php echo $i; ?>" value="<?php echo $i; ?>" class="radio"/>
                        </label>
                    <?php } ?>
                        <div id="customerreviews-rating-box" style="display: none;" class="rating-box"><div id="customerreviews-rating" class="rating" style="width: 0"></div></div>
                    </div>
                </div>
                <div class="field">
                    <label><?php echo $this->__('Rating customer support') ?></label>
                    <div class="input-box">
                    <?php for ($i = 1; $i <= 5; ++$i) { ?>
                        <label for="rating_customer_support<?php echo $i; ?>"><?php echo $i; ?>
                            <input type="radio" name="rating_customer_support" id="rating_customer_support<?php echo $i; ?>" value="<?php echo $i; ?>" class="radio"/>
                        </label>
                    <?php } ?>
                        <div id="customerreviews-rating-box" style="display: none;" class="rating-box"><div id="customerreviews-rating" class="rating" style="width: 0"></div></div>
                    </div>
                </div>
            </li>
            <li>
                <label for="message" class="required"><em>*</em><?php echo $this->__('Message') ?></label>
                <div class="input-box">
                    <textarea name="message" id="message"
                        title="<?php echo $this->__('Message') ?>"
                        class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
        <input type="hidden" name="order_id" value="<?php echo $order_id?>"/>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('customerreviewsForm', true);
//]]>
</script>